---
- name: Test Extreme VOSS switches connectivity and commands
  hosts: extreme_switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Test 1 - Check SSH connectivity
      wait_for_connection:
        timeout: 30

    - name: Test 2 - Run 'show sys-info'
      community.network.voss_command:
        commands:
          - show sys-info
      register: sys_info

    - name: Display system info
      debug:
        var: sys_info.stdout_lines

    - name: Test 3 - Run 'show running-config'
      community.network.voss_command:
        commands:
          - show running-config
      register: running_config

    - name: Display running config preview (first 20 lines)
      debug:
        msg: "{{ running_config.stdout_lines[0][:20] }}"

    - name: Test 4 - Check if backup directory is accessible
      stat:
        path: "/home/backups"
      register: backup_dir
      delegate_to: localhost

    - name: Display backup directory status
      debug:
        msg: >
          Backup directory exists: {{ backup_dir.stat.exists }},
          Writable: {{ backup_dir.stat.writeable | default('unknown') }}

    - name: Test Summary
      debug:
        msg:
          - "✅ SSH Connection: Success"
          - "✅ VOSS CLI command execution: Working"
          - "✅ Backup path: {{ 'Ready' if backup_dir.stat.exists else 'Need to create' }}"
          - "Next step: Run backup_extreme_voss.yml"
